CRITICAL_GAP = 1.5
DURATION = 100
HOR_DIM = [100, 150, 200]
VER_DIM = [150, 200, 170]
LANE_WIDTH = 3

STRAIGHT = 0
LEFT = -1
RIGHT = 1

WEST = 1
EAST = 2
NORTH = 3
SOUTH = 4

WESTL = 1
WESTR = 2
EASTL = 3
EASTR = 4
NORTHL = 5
NORTHR = 6
SOUTHL = 7
SOUTHR = 8
INITSPEED = 15      #initial entering speed of 15 m/s
FREQ = 1            #shorter = more frequent car entering

NSGREEN_EWRED = 1
NSYELLOW_EWRED = 2
NSRED_EWGREEN = 3
NSRED_EWYELLOW =4

GREEN = 1
YELLOW = 2
RED = 3

GREEN_PHASE = 8
RED_PHASE = 5
YELLOW_PHASE = 2
CLEAR_PHASE = 1

NUMBER_ARRIVAL = 5
TIME_INCREMENT = 0.1
SIM_TIME = 0

SAFE_DIST = 8
CRUISE_SPEED = 15
ACCELERATION = 10
DECELERATION = -10

DISTANCE_FROM_TRAFFIC_LIGHT = 10
OBSERVE_DISTANCE = 3
LENGTHE_CAR = 3
SCALE = 2